[package]
name = "electrum"
version = "0.1.0"
authors = ["rmoita"]
edition = "2018"

[dependencies]
ash = "0.29.0"
image = "0.20"
winit = "0.18"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.4", features = ["windef", "winuser"] }